### PR TITLE
Width/height for video

### PR DESCRIPTION
**Pull request by paneq**

### CODE REVIEW

**Comment by kaspergrubbe** [comment]
Nice change! I really like the providers that you have introduced!

## Two things:
- Could you use 1.8 syntax (for backwards compatibility, and for letting the specs pass)
- Could you introduce your awesome change in the README ? :+1:

**Comment by paneq** [comment]
Sure. Starting on it right now.

**Comment by paneq** [comment]
I think this should fix the issues.

**Comment by paneq** [comment]
The Initial solution was better for monkey patching by external developers. I think we will need to come up with a good idea of how to bring it back later. Perhaps allow people to register providers in kind of similar ways to what you can do in rails with registering custom mime types. I don't like my `Filters::Provider` class right now. But I could not find yet right object to put the responsibility of extracting proper options for proper class. I don't like where every class has access to every possible option, even those that are not needed.

**Pull request merged**
